name: Auto News Reel

on:
  workflow_dispatch: # Manual chalane ke liye

jobs:
  post-reel:
    runs-on: ubuntu-latest
    steps:
      - name: Code download karo
        uses: actions/checkout@v4

      - name: Python set karo
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # yahan change kiya

      - name: FFmpeg install karo - video ke liye zaruri
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Python package install karo
        run: |
          pip install --upgrade pip
          pip install instagrapi gnews moviepy

      - name: Reel upload karo
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: python main.py
